Update AndroidManifest.xml from OpenGapps (com.google.android.tvlauncher)
nielsvanvelzen/tv-launcher pull request #1
Opened 2021-06-26 03:08 UTC by roblav96

After decompiling the `TVLauncher.apk` found in OpenGapps `open_gapps-arm64-9.0-tvmini-20210619.zip`, I found a few useful edits, also found pointers from the https://gitlab.com/etienn01/flauncher repo.

I've been testing all day on my devices, `Nvidia Shield TV 2019 Pro`, `ADT-3 Developer Kit`, and `Chromecast with Google TV`, no problems found. =]

2021-06-26 08:28 UTC, nielsvanvelzen requested changes
Thanks for your pull request! I've left some notes (mainly options that are not needed).

2021-06-26 08:28 UTC, nielsvanvelzen commented on app/src/main/AndroidManifest.xml
> +		android:usesCleartextTraffic="true"
The app doesn't use networking (right now) and if it did it probably wouldn't allow any HTTP traffic, so this option is not needed.

2021-06-26 08:28 UTC, nielsvanvelzen commented on app/src/main/AndroidManifest.xml
> +			android:screenOrientation="landscape">
Both landscape and portrait orientations work so we don't need to force landscape mode, so this option is not needed.

2021-06-26 08:28 UTC, nielsvanvelzen commented on app/src/main/AndroidManifest.xml
> +			<intent-filter android:priority="999">
I don't think we need to set a different priority

2021-06-26 08:28 UTC, nielsvanvelzen commented on app/src/main/AndroidManifest.xml
> +	<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
The app does not use this permission right now so it shouldn't be added here.

2021-06-29 12:14 UTC, nielsvanvelzen approved these changes
Thank you!

2021-06-29 12:15 UTC, merged

2021-06-30 14:38 UTC, roblav96 commented
Cheers mate! 🍻