Implement basic favorites app display
nielsvanvelzen/tv-launcher pull request #199
Opened 2023-10-16 17:44 UTC by Kevinjil

Add a long press action to app cards. In the dropdown menu that opens, there is an add to or remove from favorites button.

A new app row above the "All apps" row is added which displays the favorite apps.

Initially, I wanted to implement a more dynamic way of defining custom sections and allowing to add apps on a per-section basis. Then, I started wondering who would use than more than 1 row anyway so I settled for a "Favorites" row. If you think sections would be preferred, I could rework this PR.

Closes 

_As I have never written anything in Kotlin or for Android TV, feel free to call out some suggestions._

2023-10-16 17:44 UTC, Kevinjil commented
Mostly written this as the lack of some form of "Favorites / highlight" was a dealbreaker for using it as main launcher ;)

2023-10-17 11:28 UTC, nielsvanvelzen commented
Thanks for the pull request! A favorite feature was always planned but I didn't make any progress yet. I've even removed the database part for it in 8d6c0334f4c9fe8c02cb7ad5a65ae07f15aaa693. I started out by testing the changes in the emulator and found a few issues:

1) The "favorites" section should be hidden when there are no favorites. Right now it looks like this:
![image](https://github.com/nielsvanvelzen/tv-launcher/assets/2305178/a5996937-b63a-46f5-8412-1c9953d8979b)

2) On Android TV there are two ways to open a context menu, either by long pressing (using the dpad center button/pointer) or by using the dedicated menu button. In my testing it only works when long pressing with a pointer. Neither the menu button nor the dpad long press work.

3) After adding/removing from favorites the context menu does not auto-close

2023-10-29 10:17 UTC, Kevinjil commented
@nielsvanvelzen I've incorporated your feedback. Long pressing for the DPAD center seems to need a custom implementation and I would rather wait for an upstream fix.

Additional features:
- Sort the apps
- Fix cache issue with app icons when adding/removing favorites

2023-12-04 18:07 UTC, nielsvanvelzen requested changes
Sorry for the slow response, was busy with a lot of other stuff.

2023-12-04 18:07 UTC, nielsvanvelzen commented on app/src/main/kotlin/nl/ndat/tvlauncher/data/entity/App.kt
>  )
I'm not a fan of these separate views for the same entity. Is this a recommended way of using androidx.room?

2023-12-04 18:07 UTC, nielsvanvelzen commented on app/src/main/kotlin/nl/ndat/tvlauncher/ui/component/card/AppCard.kt
>  package nl.ndat.tvlauncher.ui.component.card
The changes in this file have incorrect formatting, please reformat the file.

2023-12-04 18:07 UTC, nielsvanvelzen commented on app/src/main/kotlin/nl/ndat/tvlauncher/ui/component/card/AppCard.kt
> +			})
I feel like we should add our own Modifier extension function to wrap this key event & the long click so we can do something like `.onMenu { expanded = true }`

2023-12-04 18:07 UTC, nielsvanvelzen commented on app/src/main/kotlin/nl/ndat/tvlauncher/ui/component/card/AppCard.kt
> +	val expanded = remember { mutableStateOf(false) }
```suggestion
	val expanded by remember { mutableStateOf(false) }
```

Use delegated property so we can omit using `.value` everywhere

2024-09-15 14:34 UTC, nielsvanvelzen commented
Favorites are now implemented in 1c03f827ba7ed415e190f575f646bc9dec488f9f

2024-09-15 14:34 UTC, closed without merging

2024-09-24 14:59 UTC, Kevinjil commented
@nielsvanvelzen Thanks for the proper implementation :rocket: